[package]
name = "xavier-xml"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quick-xml = "0.31.0"
lazy_static = "1.4.0"
xavier-derive= { path = "../xavier_derive", optional = true }

[features]
default = ["xavier-derive"]