[package]
name = "xavier"
version = "0.1.0"
edition = "2021"

[dependencies]
quick-xml = "0.31.0"
xavier-derive = { path = "../xavier_derive", optional = true }

[features]
derive = ["xavier-derive"]

