[package]
name = "xavier-derive"
version = "0.1.1"
authors = ["Thiago Medeiros dos Santos <thiago.santos.it@gmail.com>"]
edition = "2021"

[dependencies]
syn = "2.0.53"
quote = "1.0.35"
proc-macro2 = "1.0.79"
convert_case = "0.6.0"

[lib]
proc-macro = true



